# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AText', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_questions', models.IntegerField()),
                ('Marks_for1', models.IntegerField()),
                ('Time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField()),
                ('StuName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeaName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='A',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Q',
            new_name='QText',
        ),
        migrations.AddField(
            model_name='question',
            name='AText',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='quizset',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Teacher'),
        ),
        migrations.AddField(
            model_name='answerset',
            name='Candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student'),
        ),
        migrations.AddField(
            model_name='answerset',
            name='Qno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='Author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='QuizSetNo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.QuizSet'),
            preserve_default=False,
        ),
    ]
