# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170110_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Author',
        ),
    ]
