# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_question_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='QuizSetNo',
            new_name='quizset',
        ),
    ]
