# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170111_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizset',
            name='TestName',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
