# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170111_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizset',
            name='TestName',
            field=models.CharField(default='test series', max_length=100),
        ),
    ]
